# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.brownbag.com:
  peer0.org1.brownbag.com:
  peer0.org2.brownbag.com:

networks:
  bb2:

services:

  orderer.brownbag.com:
    extends:
      file:  docker-compose-base.yaml
      service: orderer.brownbag.com
    container_name: orderer.brownbag.com
    networks:
      - bb2

  peer0.org1.brownbag.com:
    container_name: peer0.org1.brownbag.com
    extends:
      file: docker-compose-base.yaml
      service: peer0.org1.brownbag.com
    networks:
      - bb2

  peer0.org2.brownbag.com:
    container_name: peer0.org2.brownbag.com
    extends:
      file: docker-compose-base.yaml
      service: peer0.org2.brownbag.com
    networks:
      - bb2

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.2
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.brownbag.com:7051
      - CORE_PEER_LOCALMSPID=ORG1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.brownbag.com/peers/peer0.org1.brownbag.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.brownbag.com/peers/peer0.org1.brownbag.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.brownbag.com/peers/peer0.org1.brownbag.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.brownbag.com/users/Admin@org1.brownbag.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../chaincode/:/opt/gopath/src/github.com/chaincode
        - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ../cli-commands.sh:/opt/gopath/src/github.com/hyperledger/fabric/peer/cli-commands.sh
    depends_on:
      - orderer.brownbag.com
      - peer0.org1.brownbag.com
      - peer0.org2.brownbag.com
    networks:
      - bb2