# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0.
#

version: '2'

services:

  orderer.brownbag.com:
    container_name: orderer.brownbag.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/brownbag.com/orderers/orderer.brownbag.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/brownbag.com/orderers/orderer.brownbag.com/tls:/var/hyperledger/orderer/tls
        - orderer.brownbag.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.org1.brownbag.com:
    container_name: peer0.org1.brownbag.com
    extends:
      file: peer-base.yaml
      service: peer-base
    dns_search: .
    environment:
      - CORE_PEER_ID=peer0.org1.brownbag.com
      - CORE_PEER_ADDRESS=peer0.org1.brownbag.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.brownbag.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.brownbag.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.brownbag.com:7051
      - CORE_PEER_LOCALMSPID=ORG1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.brownbag.com/peers/peer0.org1.brownbag.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.brownbag.com/peers/peer0.org1.brownbag.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.brownbag.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.org2.brownbag.com:
    container_name: peer0.org2.brownbag.com
    extends:
      file: peer-base.yaml
      service: peer-base
    dns_search: .
    environment:
      - CORE_PEER_ID=peer0.org2.brownbag.com
      - CORE_PEER_ADDRESS=peer0.org2.brownbag.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.brownbag.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.brownbag.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.brownbag.com:8051
      - CORE_PEER_LOCALMSPID=ORG2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.brownbag.com/peers/peer0.org2.brownbag.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.brownbag.com/peers/peer0.org2.brownbag.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.brownbag.com:/var/hyperledger/production
    ports:
      - 8051:8051